lib/elephant_in_the_room_web/router.ex
defmodule ElephantInTheRoomWeb.Router do
  use ElephantInTheRoomWeb, :router
  import ElephantInTheRoomWeb.Plugs.SetSite
  alias ElephantInTheRoom.Auth

  pipeline :auth do
    plug(Auth.Pipeline)
  end

  pipeline :ensure_auth do
    plug(Guardian.Plug.EnsureAuthenticated)
  end

  pipeline :image_uploading do
    plug(:fetch_session)
    plug(:put_secure_browser_headers)
    plug(Auth.Pipeline)
    plug(Guardian.Plug.EnsureAuthenticated)
  end

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :site_required do
    plug(:set_site)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope path: "/images", alias: ElephantInTheRoomWeb do
    scope "/" do
      pipe_through([:image_uploading])
      post("/", ImageController, :save_image)
      post("/binary", ImageController, :save_binary_image)
    end

    get("/:name", ImageController, :get_image)
  end

  scope "/", ElephantInTheRoomWeb do
    pipe_through([:browser, :auth])

    get("/login", LoginController, :index)
    post("/login", LoginController, :login)
    get("/logout", LoginController, :logout)

    scope "/" do
      pipe_through([:site_required])
      get("/", SiteController, :public_show)
      post("/feedback", FeedbackController, :create)
      get("/latest", SiteController, :public_show_latest)
      get("/popular", SiteController, :public_show_popular)
      get("/media", SiteController, :public_show_media)
      get("/author/:author_name", AuthorController, :public_show)
      get("/post/:year/:month/:day/:slug", PostController, :public_show)
      get("/category/:category_name", CategoryController, :public_show)
      get("/tag/:tag_name", TagController, :public_show)
      get("/magazine", MagazineController, :current)
      get("/magazine/:title", MagazineController, :public_show)
      get("/magazine/:magazine_title/post/:year/:month/:day/:slug", PostController, :public_show, as: "magazine_post")
      get("/magazines", MagazineController, :public_index)
    end

    scope "/admin" do
      pipe_through([:on_admin_page, :ensure_auth])
      get("/", AdminController, :index)
      resources("/roles", RoleController, param: "role_name")
      resources("/users", UserController, param: "user_name")
      resources("/authors", AuthorController, param: "author_name")
      get("/backup", BackupController, :index)
      post("/backup/do_backup", BackupController, :do_backup)
      get("/backup/download_latest", BackupController, :download_latest)
      get("/backup/modify_settings", BackupController, :get_modify_settings)

      resources "/sites", SiteController, param: "name" do
        pipe_through(:load_site_info)
        get("/feedback", FeedbackController, :index)
        get("/feedback/:id", FeedbackController, :show)
        delete("/feedback/:id", FeedbackController, :delete)
        resources("/categories", CategoryController, param: "category_name")
        resources("/posts", PostController, param: "slug")
        resources("/tags", TagController, param: "tag_name")
        resources("/ads", AdController, param: "ad_name")
        resources "/magazines", MagazineController, param: "title", except: [:show] do
          resources("/posts", PostController, param: "slug", except: [:show])
        end
      end
    end
  end
end

lib/elephant_in_the_room_web/views/layout_view.ex
defmodule ElephantInTheRoomWeb.LayoutView do
  use ElephantInTheRoomWeb, :view
  alias ElephantInTheRoom.{Auth, Auth.Role, Auth.User, Sites, Sites.Site}
  alias ElephantInTheRoomWeb.Utils.Utils

  def get_categories(assigns, amount \\ 5)

  def get_categories(%{assigns: %{site: %{categories: categories}}}, amount) do
    categories
    |> Enum.map(&{&1.id, &1.name})
    |> Enum.split(amount)
  end

  def get_categories(_, _) do
    {[], []}
  end

  def in_current_site(conn, site_id) do
    current_site = conn.assigns[:site]

    case current_site do
      nil -> false
      _ -> current_site.id == site_id
    end
  end

  def get_logged_user(conn) do
    case Auth.get_user(conn) do
      {:ok, %User{:role => %Role{:name => role}} = user} ->
        {:ok, user, String.to_atom(role)}

      {:error, _} = error ->
        error
    end
  end

  def get_logger_user_name!(conn) do
    case get_logged_user(conn) do
      {_error, reason} -> raise "no user name found: #{reason}"
      {:ok, user, _} -> user.username
    end
  end

  def get_site_path(conn) do
    if Map.has_key?(conn.assigns, :site) do
      case conn && conn.assigns.site do
        nil ->
          login_path(conn, :login)

        _site ->
          site_path(conn, :public_show)
      end
    end
  end

  def current_site(conn) do
    conn.assigns[:site]
  end

  def get_site_name(conn) do
    site = conn.assigns[:site]

    case site do
      nil -> "Elephant in the room"
      site -> site.name
    end
  end

  def show_site_link(%Site{} = site, conn) do
    "#{to_string(conn.scheme)}://#{site.host}:#{to_string(conn.port)}"
  end

  def show_site_link(conn), do: "http://" <> conn.host

  def show_category_link(conn, category_name) do
    category_path(conn, :public_show, category_name)
    |> Utils.generate_absolute_url(conn)
  end
end

lib/elephant_in_the_room_web/templates/layout/_admin.html.eex
<link rel="stylesheet" href="/css/color-picker.min.css" media="screen">
<script src="/js/color-picker.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<link href="<%= static_path(@conn, "/css/select2.min.css") %>" rel="stylesheet"/>
<script src="<%= static_path(@conn, "/js/select2.full.min.js") %>"></script>

<div class="admin-top-bar-line"></div>

<!-- NAVIGATION BAR-->
<nav class="uk-navbar-container admin-nav-bar" uk-navbar>
  <div class="uk-navbar-left">
    <ul class="uk-navbar-nav admin-nav-options">
      <li class="uk-active nav-title">
        <a href="<%= admin_path(@conn, :index) %>">
          Elephant Admin
        </a>
      </li>
    </ul>
    <ul class="uk-navbar-nav admin-nav-options show-only-on-bigger-than-small">
      <li><a href="/">Inicio</a></li>
      <li><%= link "Cerrar Sesión", to: login_path(@conn, :logout) %></li>
    </ul>
  </div>

    <div class="uk-navbar-right show-only-on-small">
        <ul class="uk-navbar-nav admin-nav-options">
          <li>
            <a href="#" uk-toggle="target: #admin-navbar-small" >
              <i class="fas fa-bars fa-lg"></i>
            </a>
          </li>
        </ul>
    </div>
</nav>
<div id="admin-navbar-small"
     class="admin-nav-options small-admin-nav-options" aria-hidden="true" hidden>
  <ul>
    <li><a href="/">Inicio</a></li>
    <li><%= link "Cerrar Sesión", to: login_path(@conn, :logout) %></li>
  </ul>
  <div class="shadow"></div>
</div>

<!-- NAVIGATION BAR -->



<div class="uk-container  admin-body-container">

  <div uk-grid>
    <div class="uk-width-5-5 uk-width-auto@s side-bar">

      <h3> Administración </h3>

      <ul class="administation-items">
        <li>
          <%= link "Sitios",
          to: site_path(@conn, :index) %>
        </li>
        <li>
          <%= link "Autores",
          to: author_path(@conn, :index) %>
        </li>
        <li>
          <%= link "Usuarios",
          to: user_path(@conn, :index) %>
        </li>
        <li>
          <%= link "Roles",
          to: role_path(@conn, :index) %>
        </li>
        <li>
          <%= link "Respaldo",
          to: backup_path(@conn, :index) %>
        </li>
      </ul>
    </div>

    <% {crumb_path, crumb_target} = ElephantInTheRoomWeb.AdminView.
         bread_crumb(@conn, assigns[:bread_crumb]) %>
    <div class="uk-width-5-5 uk-width-expand@s administration-side">
      <div class="admin-route">
        <a class="path" href="<%= admin_path(@conn, :index) %>">
          <i class="fas fa-cogs"></i>
        </a>
        <%= for {title, url} <- crumb_path do %>
          <span class="divider">/</span>
          <a class="path" href="<%= url %>"><%= title %></a>
        <% end %>
        <%= case crumb_target do %>
          <%= {title, _} -> %>
          <span class="divider">/</span>
          <span class="path target"><%= title %></span>
          <% _ -> %>
        <% end %>
      </div>
      <div role="main">
        <%= render @view_module, @view_template, assigns %>
      </div>
    </div>
  </div>


</div>

lib/elephant_in_the_room_web/templates/layout/_category_options.html.eex
<% {categories, _more_categories} = get_categories(@conn, 10) %>

<%= if current_site(@conn) do %>
  <%= for {_cat_id, cat_name} <- categories do %>
  <li>
    <%= link cat_name,
        to: show_category_link(@conn, cat_name) %>
  </li>
  <% end %>
<% end %>

lib/elephant_in_the_room_web/templates/layout/_deps.html.eex
<link rel="stylesheet" href="<%= static_path(@conn, "/css/fonts.css") %>">
<script src="<%= static_path(@conn, "/js/app.js") %>"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css" integrity="sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ" crossorigin="anonymous">

lib/elephant_in_the_room_web/templates/layout/_feedback_form.html.eex
<% import ElephantInTheRoomWeb.Router.Helpers %>

<button class="uk-modal-close-default" type="button" uk-close></button>    
<h2 class="uk-modal-title">Sugerencias</h2>
<%= unless Enum.empty?(Phoenix.Controller.get_flash(@conn)) do %>
  <%= if (Phoenix.Controller.get_flash(@conn, :feedback_error)) != nil do %>
    <div class="uk-alert-danger uk-animation-toggle uk-animation-slide-top" uk-alert>
      <a class="uk-alert-close" uk-close></a>
      <p><%= get_flash(@conn, :feedback_error) %></p>
    </div>
  <% else %>
    <div class="uk-alert-danger uk-animation-toggle uk-animation-slide-top" uk-alert>
      <a class="uk-alert-close" uk-close></a>
      <p><%= get_flash(@conn, :feedback_ok) %></p>
    </div>
  <% end %>
<% end %>
<%= form_for @conn, feedback_path(@conn, :create), [class: "uk-form-stacked"], fn f -> %>
  <%= if Map.has_key?(@conn.assigns, :errors) do %>
    <div class="alert alert-danger">
      <p>Por favor revisa los errores a continuación.</p>
    </div>
  <% end %>

  <fieldset class="uk-fieldset">
    <div class="uk-margin">
      <%= label f, :text, "Texto", class: "uk-form-label" %>
      <%= textarea f, :text, class: "uk-form-controls uk-input" %>
      <%= error_tag f, :text %>
    </div>

    <div class="uk-margin">
      <%= label f, :email, "E-mail", class: "uk-form-label" %>
      <%= text_input f, :email, class: "uk-form-controls uk-input" %>
      <%= error_tag f, :email %>
    </div>

    <div class="uk-margin">
      <center>
        <%= submit "Enviar", class: "uk-button uk-button-primary" %>
      </center>
    </div>
  </fieldset>
<% end %>

lib/elephant_in_the_room_web/templates/layout/_navbar.html.eex
<nav class="uk-navbar-container navbar-container" uk-navbar>

  <div class="uk-navbar-left">
    <ul class="uk-navbar-nav ul-reduced">
      <li class="uk-active">
        <a href="<%= get_site_path(@conn) %>" class="navbar-title a-reduced a-title">
          <%=  get_site_name(@conn) %>
        </a>
      </li>
    </ul>
  </div>

  <div class="nav-overlay uk-navbar-right">
    <ul class="uk-navbar-nav ul-reduced">

      <li><%= link "Media", to: site_path(@conn, :public_show_media), class: "a-reduced top-link hide-on-small"%></li>

      <li><%= link "Popular", to: site_path(@conn, :public_show_popular), class: "a-reduced top-link hide-on-small"%></li>

      <li><%= link "Recientes", to: site_path(@conn, :public_show_latest), class: "a-reduced top-link hide-on-small" %></li>

      <li>
        <a href="#" class="a-reduced top-link hide-on-small">
          <span class="with-dropdown">Categorías</span>
          <span class="text-icons">
            <i class="fas fa-angle-down icon-down"></i>
            <i class="fas fa-angle-up icon-up"></i>
          </span>
          <div class="dropdown-arrow-up"> </div>
        </a>
        <div uk-dropdown="pos: bottom-center; offset: 0"
             class="uk-navbar-dropdown dropdown-container">
          <ul class="uk-nav uk-navbar-dropdown-nav">
            <%= render "_category_options.html", assigns %>
          </ul>
        </div>
      </li>

      <li>
        <a href="#" class="a-reduced top-link hide-on-small">
          <span class="with-dropdown">Revista</span>
          <span class="text-icons">
            <i class="fas fa-angle-down icon-down"></i>
            <i class="fas fa-angle-up icon-up"></i>
          </span>
          <div class="dropdown-arrow-up"> </div>
        </a>
        <div uk-dropdown="pos: bottom-center; offset: 0"
             class="uk-navbar-dropdown dropdown-container">
          <ul class="uk-nav uk-navbar-dropdown-nav">
            <li><%= link "Edición actual", to: magazine_path(@conn, :current) %></li>
            <li><a href="#"></a></li>
            <li><%= link "Todas las ediciones", to: magazine_path(@conn, :public_index) %></li>
          </ul>
        </div>
      </li>

       <li>
        <a href="#" class="a-reduced top-link hide-on-small">
          <span class="with-dropdown">Más</span>
          <span class="text-icons">
            <i class="fas fa-angle-down icon-down"></i>
            <i class="fas fa-angle-up icon-up"></i>
          </span>
          <div class="dropdown-arrow-up"> </div>
        </a>
        <div uk-dropdown="pos: bottom-right; offset: 0"
             class="uk-navbar-dropdown dropdown-container">
          <ul class="uk-nav uk-navbar-dropdown-nav">
            <li class="uk-nav-header">Usuario</li>
            <li class="uk-nav-divider"></li>
            <%= render "_user_options.html", assigns %>
            <li class="uk-nav-header">Sitios</li>
            <li class="uk-nav-divider"></li>
            <%= render "_site_options.html", assigns %>
          </ul>
        </div>
      </li>
    </ul>
  </div>
</nav>

<div class="mini-navbar-container" uk-grid>
  <div class="uk-width-1-5 uk-text-center">
    <div class="element">
      <%= link to: site_path(@conn, :public_show_popular) do %>
        <div class="mini-icon"><i class="fas fa-chart-line fa-2x"></i></div>
        <div class="mini-description">Popular</div>
      <% end %>
    </div>
  </div>
  <div class="uk-width-1-5 uk-text-center">
    <div class="element">
      <%= link to: site_path(@conn, :public_show_latest) do %>
        <div class="mini-icon"><i class="fas fa-clock fa-2x"></i></div>
        <div class="mini-description">Recientes</div>
      <% end %>
    </div>
  </div>
  <div class="uk-width-1-5 uk-text-center">
    <div class="element" uk-toggle="target: #offcanvas-section">
      <div class="mini-icon"><i class="fas fa-bars fa-2x"></i></div>
      <div class="mini-description">Categorías</div>
    </div>
  </div>
  <div class="uk-width-1-5 uk-text-center">
    <div class="element" uk-toggle="target: #offcanvas-magazine">
      <div class="mini-icon"><i class="fas fa-book fa-2x"></i></div>
      <div class="mini-description">Revista</div>
    </div>
  </div>
  <div class="uk-width-1-5 uk-text-center">
    <div class="element" uk-toggle="target: #offcanvas-more">
      <div class="mini-icon"><i class="fas fa-plus fa-2x"></i></div>
      <div class="mini-description">Más</div>
    </div>
  </div>
</div>


<!-- OFFCANVAS -->

<div id="offcanvas-section"
     class="mini-navbar-offcanvas"
     uk-offcanvas="mode: none; overlay: true">
  <div class="uk-offcanvas-bar">
    <button class="uk-offcanvas-close" type="button" uk-close></button>
    <h3>Categorías</h3>
    <div class="nav-divider"></div>
    <ul class="uk-nav uk-nav-default">
      <%= render "_category_options.html", assigns %>
    </ul>
  </div>
</div>


<div id="offcanvas-magazine"
     class="mini-navbar-offcanvas"
     uk-offcanvas="mode: none; overlay: true">
  <div class="uk-offcanvas-bar">
    <button class="uk-offcanvas-close" type="button" uk-close></button>
    <h3>Revista</h3>
    <div class="nav-divider"></div>
    <ul class="uk-nav uk-nav-default">
      <li><%= link "Edición actual", to: magazine_path(@conn, :current) %></li>
      <li><a href="#">Todas las ediciones</a></li>
    </ul>
  </div>
</div>


<div id="offcanvas-more"
     class="mini-navbar-offcanvas"
     uk-offcanvas="mode: none; overlay: true">
  <div class="uk-offcanvas-bar">
    <button class="uk-offcanvas-close" type="button" uk-close></button>
    <h3>Más</h3>
    <div class="nav-divider"></div>
    <ul class="uk-nav uk-nav-default">
      <%= render "_user_options.html", assigns %>
    </ul>
    <div class="nav-divider"></div>
    <ul class="uk-nav uk-nav-default">
      <%= render "_site_options.html", assigns %>
    </ul>
  </div>
</div>

lib/elephant_in_the_room_web/templates/layout/_normal_footer.html.eex
<%= if assigns[:site] do %>
  <div class="uk-grid-collapse uk-flex-row footer uk-flex-center" uk-grid>
      <!-- footer -->
      <div class="uk-width-1-1 uk-margin-small-top footer-card uk-flex uk-flex-center  uk-text-left@m" uk-grid>
        <div class="uk-width-1-1@s uk-width-auto@m">
          <ul class="uk-nav uk-nav-default">
            <li class="uk-active"><a href="#"><strong>Usuario</strong></a></li>
            <%= render "_user_options.html", assigns %>
          </ul>
        </div>
        <div class="uk-width-1-1@s uk-width-auto@m">
          <ul class="uk-nav uk-nav-default">
            <li class="uk-active"><a href="#"><strong>Categorías</strong></a></li>
            <%= render "_category_options.html", assigns %>
          </ul>
        </div>
        <div class="uk-width-1-1@s uk-width-auto@m">
          <ul class="uk-nav uk-nav-default">
            <li class="uk-active"><a href="#"><strong>Sitios</strong></a></li>
            <%= render "_site_options.html", assigns %>
          </ul>
        </div>
        <div class="uk-width-1-1@s uk-width-auto@m">
          <h1>
              <%= @site.name %>
          </h1>
        </div>
      </div>
      <hr>
    </div>
<% end %>

lib/elephant_in_the_room_web/templates/layout/_site_options.html.eex
<%= if assigns[:site_list] do %>
  <%= for site <- Enum.take(@site_list, 7) do %>
    <li>
      <%= link site.name, to: show_site_link(site, @conn) %>
    </li>
  <% end %>
<% end %>

lib/elephant_in_the_room_web/templates/layout/_social_meta.html.eex
<%= if assigns[:meta] do %>
  <%= if Map.has_key?(@meta, :title) and @meta.title do %>
    <meta property="og:title" content="<%= @meta.title %>" />
    <title> <%= @meta.title %> </title>
  <% else %>
    <%= if assigns[:site] do %>
      <title> @site.title </title>
    <% end %>
  <% end %>

  <%= if Map.has_key?(@meta, :url) and @meta.url do %>
    <meta property="og:url" content="<%= @meta.url %>" />
  <% end %>
  <%= if @meta.type do %>
    <meta property="og:type" content="<%= @meta.type %>" />
  <% end %>

  <%= if Map.has_key?(@meta, :description) and @meta.description do %>
    <meta property="og:description" content="<%= @meta.description %>" />
  <% end %>

  <%= if Map.has_key?(@meta, :image) and @meta.image do %>
    <meta property="og:image" content="<%= @meta.image %>" />
  <% end %>

<% else %>
  <%= if assigns[:site] do %>
    <title> <%= @site.title %></title>
  <% else %>
    <title>Elephant In The Room</title>
  <% end %>
<% end %>

lib/elephant_in_the_room_web/templates/layout/_user_options.html.eex
<% login = get_logged_user(@conn) %>
<%= case login do %>
  <% {:error,  _} -> %>
  <li>
    <a href="<%= login_path(@conn, :login) %>">
      Iniciar Sesión
    </a>
  </li>
  <% {:ok, user, _} -> %>
  <li>
    <a>
      <i class="fas fa-user"></i>
      <%= user.username %>
    </a>
  </li>
<% end %>

<%= case login do %>
  <% {:ok, _, _} -> %>
  <li>
    <%= link to: login_path(@conn, :logout) do %>
      <i class="fas fa-sign-out-alt"></i>
      Cerrar Sesión
    <% end %>
  </li>
  <% _ -> %>
<% end %>

<%= case login do %>
  <% {:ok, _user, :admin} -> %>
  <li>
    <a href="<%= admin_path(@conn, :index) %>">
      Administración
    </a>
  </li>
  <% _ -> %>
<% end %>

lib/elephant_in_the_room_web/templates/layout/app.html.eex
<% alias ElephantInTheRoom.Sites 
   alias ElephantInTheRoomWeb.FeedbackView
%>

<!DOCTYPE html>
<html lang="en" prefix="og: http://ogp.me/ns#">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tag() %>
    <%= render "_social_meta.html", assigns %>

    <%= if Map.has_key?(assigns, :site) and @site.favicon != nil do %>
      <link rel="icon" type="image/x-icon" href="<%= "#{@site.favicon}" %>">
    <% end %>

    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <%= if assigns[:admin] do %>
    <body class="admin-body-root">
      <%= render "_admin.html", assigns %>
    </body>
    <%= render "_deps.html", assigns %>
  <% else %>
    <% assigns = Map.merge(assigns, %{site_list: Sites.list_site_no_preload()}) %>
    <body>
      <div class="uk-offcanvas-content">
        <%= render "_navbar.html", assigns %>
        <button uk-toggle="target: #feedback-form" type="button" class="uk-button uk-button-secondary uk-button-small feedback-button">
          Sugerencias
        </button>
        <div id="feedback-form" uk-modal>
          <div class="uk-modal-dialog uk-modal-body">
            <%= FeedbackView.render "feedback_form.html", assigns %>
          </div>
        </div>
        </div>
        <div role="main">
          <%= render @view_module, @view_template, assigns %>
        </div>
        <div>
          <%= render "_normal_footer.html", assigns %>
        </div>
      </div>
    </body>
    <%= render "_deps.html", assigns %>
  <% end %>
</html>