lib/elephant_in_the_room_web/router.ex
defmodule ElephantInTheRoomWeb.Router do
  use ElephantInTheRoomWeb, :router
  import ElephantInTheRoomWeb.Plugs.SetSite
  alias ElephantInTheRoom.Auth

  pipeline :auth do
    plug(Auth.Pipeline)
  end

  pipeline :ensure_auth do
    plug(Guardian.Plug.EnsureAuthenticated)
  end

  pipeline :image_uploading do
    plug(:fetch_session)
    plug(:put_secure_browser_headers)
    plug(Auth.Pipeline)
    plug(Guardian.Plug.EnsureAuthenticated)
  end

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :site_required do
    plug(:set_site)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope path: "/images", alias: ElephantInTheRoomWeb do
    scope "/" do
      pipe_through([:image_uploading])
      post("/", ImageController, :save_image)
      post("/binary", ImageController, :save_binary_image)
    end

    get("/:name", ImageController, :get_image)
  end

  scope "/", ElephantInTheRoomWeb do
    pipe_through([:browser, :auth])

    get("/login", LoginController, :index)
    post("/login", LoginController, :login)
    get("/logout", LoginController, :logout)

    scope "/" do
      pipe_through([:site_required])
      get("/", SiteController, :public_show)
      post("/feedback", FeedbackController, :create)
      get("/latest", SiteController, :public_show_latest)
      get("/popular", SiteController, :public_show_popular)
      get("/media", SiteController, :public_show_media)
      get("/author/:author_name", AuthorController, :public_show)
      get("/post/:year/:month/:day/:slug", PostController, :public_show)
      get("/category/:category_name", CategoryController, :public_show)
      get("/tag/:tag_name", TagController, :public_show)
      get("/magazine", MagazineController, :current)
      get("/magazine/:title", MagazineController, :public_show)
      get("/magazine/:magazine_title/post/:year/:month/:day/:slug", PostController, :public_show, as: "magazine_post")
      get("/magazines", MagazineController, :public_index)
    end

    scope "/admin" do
      pipe_through([:on_admin_page, :ensure_auth])
      get("/", AdminController, :index)
      resources("/roles", RoleController, param: "role_name")
      resources("/users", UserController, param: "user_name")
      resources("/authors", AuthorController, param: "author_name")
      get("/backup", BackupController, :index)
      post("/backup/do_backup", BackupController, :do_backup)
      get("/backup/download_latest", BackupController, :download_latest)
      get("/backup/modify_settings", BackupController, :get_modify_settings)

      resources "/sites", SiteController, param: "name" do
        pipe_through(:load_site_info)
        get("/feedback", FeedbackController, :index)
        get("/feedback/:id", FeedbackController, :show)
        delete("/feedback/:id", FeedbackController, :delete)
        resources("/categories", CategoryController, param: "category_name")
        resources("/posts", PostController, param: "slug")
        resources("/tags", TagController, param: "tag_name")
        resources("/ads", AdController, param: "ad_name")
        resources "/magazines", MagazineController, param: "title", except: [:show] do
          resources("/posts", PostController, param: "slug", except: [:show])
        end
      end
    end
  end
end

lib/elephant_in_the_room/posts/category.ex
defmodule ElephantInTheRoom.Posts.Category do
  use ElephantInTheRoom.Schema
  import Ecto.Changeset
  alias ElephantInTheRoom.Posts.{Category, Post}
  alias ElephantInTheRoom.Sites.Site

  schema "categories" do
    field(:description, :string)
    field(:name, :string)

    belongs_to(:site, Site, foreign_key: :site_id)

    many_to_many(
      :posts,
      Post,
      join_through: "posts_categories",
      on_replace: :delete,
      on_delete: :delete_all
    )

    timestamps()
  end

  @doc false
  def changeset(%Category{} = category, attrs) do
    category
    |> cast(attrs, [:name, :description, :site_id])
    |> validate_required([:name, :description, :site_id], message: "Campo requerido.")
    |> unique_constraint(:name, message: "Ya existe.")
  end
end

lib/elephant_in_the_room_web/controllers/category_controller.ex
defmodule ElephantInTheRoomWeb.CategoryController do
  use ElephantInTheRoomWeb, :controller
  import Ecto.Query
  import ElephantInTheRoomWeb.Utils.Utils, only: [get_page: 1]
  alias ElephantInTheRoom.{Posts, Posts.Category, Repo, Sites, Sites.Site}

  def index(%{assigns: %{site: site}} = conn, params) do
    page =
      case params do
        %{"page" => page_number} ->
          Category
          |> where([c], c.site_id == ^site.id)
          |> Repo.paginate(page: page_number)

        %{} ->
          Category
          |> where([c], c.site_id == ^site.id)
          |> Repo.paginate(page: 1)
      end

    render(
      conn,
      "index.html",
      categories: page.entries,
      site: site,
      page_number: page.page_number,
      page_size: page.page_size,
      total_pages: page.total_pages,
      total_entries: page.total_entries,
      bread_crumb: [:sites, site, :categories]
    )
  end

  def new(%{assigns: %{site: site}} = conn, _) do
    changeset =
      %Category{site_id: site.id}
      |> Posts.change_category()

    render(conn, "new.html", changeset: changeset, site: site)
  end

  def create(%{assigns: %{site: site}} = conn, %{"category" => category_params}) do
    case Posts.create_category(site, category_params) do
      {:ok, category} ->
        conn
        |> put_flash(:info, "Category created successfully.")
        |> redirect(
          to: site_category_path(conn, :show, URI.encode(site.name), URI.encode(category.name))
        )

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset, site: site)
    end
  end

  def show(%{assigns: %{site: site}} = conn, %{"site_name" => site_name, "category_name" => name}) do
    cat_site = Sites.from_name!(site_name, Site)
    category = Sites.from_name!(name, cat_site.id, Category)
    render(conn, "show.html", category: category, site: site)
  end

  def public_show(conn, %{"category_name" => name} = params) do
    page = get_page(params)

    site = conn.assigns.site

    category =
      Sites.from_name!(name, Category)
      |> Repo.preload(posts: :categories, posts: :author)

    posts = Sites.get_category_with_posts(site, category.id, amount: 10, page: page)
    category = %{category | posts: posts}

    render(conn, "public_show.html", category: category, site: site, page: page)
  end

  def edit(%{assigns: %{site: site}} = conn, %{"category_name" => name}) do
    category = Sites.from_name!(name, Category)
    changeset = Posts.change_category(category)
    render(conn, "edit.html", site: site, category: category, changeset: changeset)
  end

  def update(%{assigns: %{site: site}} = conn, %{
        "category_name" => name,
        "category" => category_params
      }) do
    category = Sites.from_name!(name, Category)

    case Posts.update_category(category, category_params) do
      {:ok, category} ->
        conn
        |> put_flash(:info, "Category updated successfully.")
        |> redirect(
          to: site_category_path(conn, :show, URI.encode(site.name), URI.encode(category.name))
        )

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", category: category, changeset: changeset)
    end
  end

  def delete(%{assigns: %{site: site}} = conn, %{"category_name" => name}) do
    category = Sites.from_name!(name, Category)
    {:ok, _category} = Posts.delete_category(category)

    conn
    |> put_flash(:info, "Category deleted successfully.")
    |> redirect(to: site_category_path(conn, :index, URI.encode(site.name)))
  end
end

lib/elephant_in_the_room_web/views/category_view.ex
defmodule ElephantInTheRoomWeb.CategoryView do
  use ElephantInTheRoomWeb, :view
  import Ecto.Query
  alias ElephantInTheRoom.{Posts.Post, Repo}
  alias ElephantInTheRoomWeb.Utils.Utils

  def get_top_featured_post(_conn, posts) do
    case posts do
      [top | _] -> {:ok, top}
      [] -> {:error, :no_top_featured}
    end
  end

  def get_important_posts(_conn, posts) do
    case posts do
      [_top | rest] ->
        {:ok, Enum.take(rest, 3)}

      [] ->
        {:error, :no_important_posts}
    end
  end

  def get_normal_posts(_conn, posts) do
    case posts do
      [_ | normal_posts] ->
        {:ok, Enum.drop(normal_posts, 4)}

      _ ->
        {:error, :no_normal_posts}
    end
  end

  def number_of_posts(category) do
    from(
      p in "posts_categories",
      where: p.category_id == type(^category.id, Ecto.UUID),
      select: count(p.post_id)
    )
    |> Repo.one()
  end

  def latest_posts(category, amount \\ 4) do
    cat_with_posts = Repo.preload(category, :posts)
    Enum.take(cat_with_posts.posts, amount)
  end

  def show_site_link(conn) do
    site_path(conn, :public_show)
  end

  def show_post_link(conn, %Post{inserted_at: date, slug: slug}) do
    post_path(conn, :public_show, date.year, date.month, date.day, slug)
    |> Utils.generate_absolute_url(conn)
  end
end

lib/elephant_in_the_room_web/templates/category/_post_card.html.eex
<style>
.card-image {
    width: 200px;
    height: 120px;
}

/* resize images */
.card-image img {
    width: 100%;
    height: auto;
}
</style>
<div class="uk-card uk-card-default uk-grid-margin uk-card-hover">
    <div class="uk-card-media-top card-image ">
        <img class="" src=<%= @post.image%> alt="">
    </div>
    <div class="uk-card-header">
        <h3 class="uk-card-title"><strong><%= @post.title %></strong></h3>
    </div>

    <div class="uk-card-footer">
        <strong>
            <%= link "Read More", to: site_post_path(@conn, :show, @post.site_id, @post), 
                class: "uk-button uk-button-text" %>
        </strong>
    </div>
</div>

lib/elephant_in_the_room_web/templates/category/edit.html.eex
<div class="row">
  <div class="col-xs-0 col-md-1 col-lg-2"></div>
  <div class="col-xs-12 col-md-10 col-lg-8">
    <div class="el-form uk-flex uk-flex-center">
      <div class="uk-card uk-card-default">

        <div class="uk-card-header">
          <div class="uk-grid-small uk-flex-middle" uk-grid>
            <div class="uk-width-expand">
              <h3 class="uk-card-title uk-margin-remove-bottom">
                <div><center><legend class="uk-legend">Editar Categería</legend></center></div>
              </h3>
            </div>
          </div>
        </div>

        <div class="uk-card-body">
          <%= render "form.html", Map.put(assigns, :action, 
            site_category_path(@conn, :update, URI.encode(@site.name), URI.encode(@category.name))) %>
        </div>
      </div>
    </div>
  </div>
</div>

<span><%= link "Regresar", to: site_category_path(@conn, :index, URI.encode(@site.name)) %></span>

lib/elephant_in_the_room_web/templates/category/form.html.eex
<%= form_for @changeset, @action, [class: "uk-form-stacked"], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Por favor revisa los errores a continuación.</p>
    </div>
  <% end %>

  <fieldset class="uk-fieldset">
    <div class="uk-margin">
      <%= label f, :name, "Nombre", class: "uk-form-label field-required" %>
      <%= text_input f, :name, class: "uk-form-controls uk-input" %>
      <%= error_tag f, :name %>
    </div>

    <div class="uk-margin">
      <%= label f, :description, "Descripción", class: "uk-form-label field-required" %>
      <%= textarea f, :description, class: "uk-form-controls uk-input" %>
      <%= error_tag f, :description %>
    </div>

    <div class="uk-margin">
      <center>
        <%= submit "Enviar", class: "uk-button uk-button-primary" %>
      </center>
    </div>
  </fieldset>
<% end %>

lib/elephant_in_the_room_web/templates/category/index.html.eex
<div class="admin-title">
  <span class="title-text"> Categorías </span>
  <div "admin-title-options">
    <a class="uk-button uk-button-primary uk-button-small admin-mini-button"
       href="<%= site_category_path(@conn, :new, URI.encode(@site.name)) %>">
      Crear categoría
    </a>
  </div>
</div>
<p><%= "Página: #{@page_number}/#{@total_pages}" %></p>
<table class="uk-table uk-table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <%= for category <- @categories do %>
        <tr>
          <td>
            <%= link category.name, to: site_category_path(@conn, :show, URI.encode(@site.name), URI.encode(category.name)), 
              class: "a" %>
          </td>
          <td class="text-right">
            <span>
              <%= link "", to: site_category_path(@conn, :edit, URI.encode(@site.name), URI.encode(category.name)), 
                class: "el-menu-icon fa fa-edit" %>
            </span>
            <span>
              <%= link "", to: site_category_path(@conn, :delete, URI.encode(@site.name), URI.encode(category.name)), 
                method: :delete, data: [confirm: "¿Estás seguro?"], 
                class: "el-menu-icon fa fa-trash-alt" %>
            </span>
          </td>
        </tr>
    <% end %>
  </tbody>
</table>

<%= case compare(@page_number, @total_pages) do %>
  <% :equal -> %>
    <span><%= link "", to: site_category_path(@conn, :index, @site, page: @page_number - 1), class: "el-arrow-icon fa fa-arrow-left fa-2x" %></span>
  <% :lesser -> %>
    <span><%= link "", to: site_category_path(@conn, :index, @site, page: @page_number + 1), class: "el-arrow-icon fa fa-arrow-left fa-2x" %></span>
    <span><%= link "", to: site_category_path(@conn, :index, @site, page: @page_number - 1), class: "el-arrow-icon fa fa-arrow-right fa-2x" %></span>
  <% :first -> %>
    <span><%= link "", to: site_category_path(@conn, :index, @site, page: @page_number + 1), class: "el-arrow-icon fa fa-arrow-right fa-2x" %></span>
  <% _ -> %>
<% end %>

<br>

<span><%= link "Regresar", to: site_path(@conn, :show, URI.encode(@site.name)) %></span>

lib/elephant_in_the_room_web/templates/category/new.html.eex
<div class="row">
  <div class="col-xs-0 col-md-1 col-lg-2"></div>
  <div class="col-xs-12 col-md-10 col-lg-8">
    <div class="el-form uk-flex uk-flex-center">
      <div class="uk-card uk-card-default">

        <div class="uk-card-header">
          <div class="uk-grid-small uk-flex-middle" uk-grid>
            <div class="uk-width-expand">
              <h3 class="uk-card-title uk-margin-remove-bottom">
                <legend class="uk-legend">Nueva Categoría</legend>
              </h3>
            </div>
          </div>
        </div>

        <div class="uk-card-body">
          <%= render "form.html", Map.put(assigns, :action, site_category_path(@conn, :create, URI.encode(@site.name))) %>
        </div>
      </div>
    </div>
  </div>
</div>

<span><%= link "Regresar", to: site_category_path(@conn, :index, URI.encode(@site.name)) %></span>

lib/elephant_in_the_room_web/templates/category/public_show.html.eex
<% alias ElephantInTheRoomWeb.{PostView, SiteView} %>

<div class="uk-container uk-container-small">
  <h1 class="uk-heading-primary uk-heading-divider uk-text-bold uk-text-uppercase uk-margin-top category-title"><%= @category.name %></h1>

  <div class="uk-padding">
    <%= unless Enum.empty?(@category.posts) do %>
      <% [main_post | other_posts] = @category.posts %>
      <div class="category-main-post">
        <% link_main_post = SiteView.show_link_with_date @conn, main_post %>
        <div class="uk-width-1-1 uk-margin-bottom">
          <%= link to: link_main_post do %>
            <div class="image" style="background-image: url('<%= main_post.thumbnail %>')">
              <div class="media-button <%= SiteView.media_button_by_type(main_post) %>"></div>
            </div>
          <% end %>
        </div>
        <div class="uk-width-1-1 uk-text-center uk-text-left@s">
          <h2><%= link main_post.title, to: link_main_post, class: "uk-margin-small-bottom uk-text-bold uk-text-uppercase" %></h2>
          <p class="uk-visible@s"><%= main_post.abstract %></p>
          <%= if main_post.author do %>
            <%= link main_post.author.name, to: author_path(@conn, :public_show, URI.encode(main_post.author.name)), class: "uk-text-capitalize uk-text-bold" %>
          <% end %>
          <p><%= PostView.show_date(main_post.inserted_at) %></p>
        </div>
      </div>
      <hr>

      <%= for post <- other_posts do %>
        <% link_post = SiteView.show_link_with_date @conn, post %>
        <div class="category-posts" uk-grid>
          <div class="uk-width-1-2">
            <%= link to: link_post do %>
              <div class="image" style="background-image: url('<%= post.thumbnail %>')">
                <div class="media-button <%= SiteView.media_button_by_type(post) %>"></div>
              </div>
            <% end %>
          </div>
          <div class="uk-width-1-2">
            <h2><%= link post.title, to: link_post, class: "uk-margin-small-bottom uk-text-bold uk-text-uppercase" %></h2>
            <p class="uk-visible@s"><%= post.abstract %></p>
            <%= if post.author do %>
              <%= link post.author.name, to: author_path(@conn, :public_show, URI.encode(post.author.name)), class: "uk-text-capitalize uk-text-bold author" %>
            <% end %>
            <p><%= PostView.show_date(post.inserted_at) %></p>
          </div>
        </div>
        <hr>
      <% end %>

      <%= if Enum.at(other_posts,0) != nil do %>
        <%= link "Siguiente",
              to: "#{category_path(@conn, :public_show, URI.encode(@category.name))}?page=#{@page+1}" %>
      <% end %>

    <% end %>
  </div>
</div>

lib/elephant_in_the_room_web/templates/category/show.html.eex
<h2><%= @site.name %>&nbsp;&lt;&nbsp;Categorías</h2>


<div class="uk-card uk-card-default uk-width-1-2@m">
    <div class="uk-card-header">
        <div class="uk-grid-small uk-flex-middle" uk-grid>
            <div class="uk-width-expand">
                <center>
                  <h3 class="uk-card-title uk-margin-remove-bottom">
                    <strong><%= @category.name %></strong>
                  </h3>
                  <center><p><%= @category.description %></p></center>

                </center>
            </div>
        </div>
    </div>
    <div class="uk-card-body">
        <center><p>Artículos: <%= number_of_posts(@category) %> </p></center>
        Últimos artículos en esta categoría:
        <%= for post <- latest_posts(@category) do %>
            <p>
              <%= link post.title, to: show_post_link(@conn, post), class: "a" %>
            </p>
        <% end %>
    </div>
    <div class="uk-card-footer">
      <div class="uk-align-right">
        <span><%= link "Editar", to: site_category_path(@conn, :edit, URI.encode(@site.name), URI.encode(@category.name)), class: "uk-button" %></span>
        <span><%= link "Regresar", to: site_category_path(@conn, :index, URI.encode(@site.name)), class: "uk-button" %></span>
      </div>
    </div>
</div>