lib/elephant_in_the_room_web/router.ex
defmodule ElephantInTheRoomWeb.Router do
  use ElephantInTheRoomWeb, :router
  import ElephantInTheRoomWeb.Plugs.SetSite
  alias ElephantInTheRoom.Auth

  pipeline :auth do
    plug(Auth.Pipeline)
  end

  pipeline :ensure_auth do
    plug(Guardian.Plug.EnsureAuthenticated)
  end

  pipeline :image_uploading do
    plug(:fetch_session)
    plug(:put_secure_browser_headers)
    plug(Auth.Pipeline)
    plug(Guardian.Plug.EnsureAuthenticated)
  end

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :site_required do
    plug(:set_site)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope path: "/images", alias: ElephantInTheRoomWeb do
    scope "/" do
      pipe_through([:image_uploading])
      post("/", ImageController, :save_image)
      post("/binary", ImageController, :save_binary_image)
    end

    get("/:name", ImageController, :get_image)
  end

  scope "/", ElephantInTheRoomWeb do
    pipe_through([:browser, :auth])

    get("/login", LoginController, :index)
    post("/login", LoginController, :login)
    get("/logout", LoginController, :logout)

    scope "/" do
      pipe_through([:site_required])
      get("/", SiteController, :public_show)
      post("/feedback", FeedbackController, :create)
      get("/latest", SiteController, :public_show_latest)
      get("/popular", SiteController, :public_show_popular)
      get("/media", SiteController, :public_show_media)
      get("/author/:author_name", AuthorController, :public_show)
      get("/post/:year/:month/:day/:slug", PostController, :public_show)
      get("/category/:category_name", CategoryController, :public_show)
      get("/tag/:tag_name", TagController, :public_show)
      get("/magazine", MagazineController, :current)
      get("/magazine/:title", MagazineController, :public_show)
      get("/magazine/:magazine_title/post/:year/:month/:day/:slug", PostController, :public_show, as: "magazine_post")
      get("/magazines", MagazineController, :public_index)
    end

    scope "/admin" do
      pipe_through([:on_admin_page, :ensure_auth])
      get("/", AdminController, :index)
      resources("/roles", RoleController, param: "role_name")
      resources("/users", UserController, param: "user_name")
      resources("/authors", AuthorController, param: "author_name")
      get("/backup", BackupController, :index)
      post("/backup/do_backup", BackupController, :do_backup)
      get("/backup/download_latest", BackupController, :download_latest)
      get("/backup/modify_settings", BackupController, :get_modify_settings)

      resources "/sites", SiteController, param: "name" do
        pipe_through(:load_site_info)
        get("/feedback", FeedbackController, :index)
        get("/feedback/:id", FeedbackController, :show)
        delete("/feedback/:id", FeedbackController, :delete)
        resources("/categories", CategoryController, param: "category_name")
        resources("/posts", PostController, param: "slug")
        resources("/tags", TagController, param: "tag_name")
        resources("/ads", AdController, param: "ad_name")
        resources "/magazines", MagazineController, param: "title", except: [:show] do
          resources("/posts", PostController, param: "slug", except: [:show])
        end
      end
    end
  end
end

lib/elephant_in_the_room/sites/feedback.ex
defmodule ElephantInTheRoom.Sites.Feedback do
  use ElephantInTheRoom.Schema
  import Ecto.Changeset
  alias ElephantInTheRoom.Sites.{Feedback, Site}

  schema "feedbacks" do
    field(:email, :string)
    field(:text, :string)

    belongs_to(:site, Site)

    timestamps()
  end

  @doc false
  def changeset(%Feedback{} = feedback, attrs) do
    feedback
    |> cast(attrs, [:email, :text, :site_id])
    |> validate_required([:text], message: "Texto requerido.")
    |> validate_length(:text, max: 300, message: "La longitud máxima del texto es 300 caracteres.")
    |> validate_format(:email, ~r/.+@.+\..+/i, message: "E-mail con formato incorrecto.")
  end
end

lib/elephant_in_the_room_web/controllers/feedback_controller.ex
defmodule ElephantInTheRoomWeb.FeedbackController do
  use ElephantInTheRoomWeb, :controller
  plug(:put_layout, false when action == :create)
  alias ElephantInTheRoom.{Repo, Sites, Sites.Feedback, Sites.Site}
  import Ecto.Query

  def index(%{assigns: %{site: site}} = conn, params) do
    feedbacks =
      case params do
        %{"page" => page_number} ->
          Feedback
          |> where([f], f.site_id == ^site.id)
          |> Repo.paginate(page: page_number)

        %{} ->
          Feedback
          |> where([c], c.site_id == ^site.id)
          |> Repo.paginate(page: 1)
      end

    render(
      conn,
      "index.html",
      feedbacks: feedbacks,
      site: site,
      bread_crumb: [:sites, site, :feedbacks]
    )
  end

  def create(%{assigns: %{site: site}} = conn, params) do
    case Sites.create_feedback(site, params) do
      {:ok, _feedback} ->
        conn
        |> put_flash(:feedback_ok, "Feedback creado satisfactoriamente.")
        |> render("feedback_form.html")

      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_errors(changeset)
        |> render("feedback_form.html", changeset: changeset)
    end
  end

  def show(conn, %{"site_name" => site_name, "id" => id}) do
    feedback_site = Sites.from_name!(site_name, Site)
    feedback = Sites.get_feedback!(feedback_site, id)
    render(conn, "show.html", feedback: feedback, site: feedback_site)
  end

  def delete(conn, %{"site_name" => site_name, "id" => id}) do
    feedback_site = Sites.from_name!(site_name, Site)
    feedback = Sites.get_feedback!(feedback_site, id)
    {:ok, _feedback} = Sites.delete_feedback(feedback)

    conn
    |> redirect(to: site_feedback_path(conn, :index, site_name))
  end

  defp put_errors(conn, changeset) do
    changeset.errors
    |> Enum.map(fn {k, v} -> {k, elem(v, 0)} end)
    |> Enum.reduce(conn, fn {_k, err}, connection ->
      put_flash(connection, :feedback_error, "Error: #{err}")
    end)
  end
end

lib/elephant_in_the_room_web/views/feedback_view.ex
defmodule ElephantInTheRoomWeb.FeedbackView do
  use ElephantInTheRoomWeb, :view

end

lib/elephant_in_the_room_web/templates/feedback/feedback_form.html.eex
<% import ElephantInTheRoomWeb.Router.Helpers %>

<div class="feedback-form-body">
  <button class="uk-modal-close-default" type="button" uk-close></button>    
  <h2 class="uk-modal-title">Sugerencias</h2>
  <%= unless Enum.empty?(Phoenix.Controller.get_flash(@conn)) do %>
    <%= if (Phoenix.Controller.get_flash(@conn, :feedback_error)) != nil do %>
      <div class="uk-alert-danger uk-animation-toggle uk-animation-slide-top" uk-alert>
        <a class="uk-alert-close" uk-close></a>
        <p><%= get_flash(@conn, :feedback_error) %></p>
      </div>
    <% else %>
      <div class="uk-alert-success uk-animation-toggle uk-animation-slide-top" uk-alert>
        <a class="uk-alert-close" uk-close></a>
        <p><%= get_flash(@conn, :feedback_ok) %></p>
      </div>
    <% end %>
  <% end %>
  <%= form_for @conn, feedback_path(@conn, :create), [class: "uk-form-stacked"], fn f -> %>
    <%= if Map.has_key?(@conn.assigns, :errors) do %>
      <div class="alert alert-danger">
        <p>Por favor revisa los errores a continuación.</p>
      </div>
    <% end %>

    <fieldset class="uk-fieldset">
      <div class="uk-margin">
        <%= label f, :text, "Texto", class: "uk-form-label" %>
        <%= textarea f, :text, class: "feedback-text uk-form-controls uk-textarea", rows: "4", cols: "50" %>
        <%= error_tag f, :text %>
      </div>

      <div class="uk-margin">
        <%= label f, :email, "E-mail", class: "uk-form-label" %>
        <%= text_input f, :email, class: "feedback-email uk-form-controls uk-input" %>
        <%= error_tag f, :email %>
      </div>

      <div class="uk-margin">
        <center>
          <%= submit "Enviar", class: "feedback-submit uk-button uk-button-primary" %>
        </center>
      </div>
    </fieldset>
  <% end %>
</div>

lib/elephant_in_the_room_web/templates/feedback/index.html.eex
<div class="admin-title">
  <span class="title-text"> Sugerencias </span>
</div>
<p><%= "Página: #{@feedbacks.page_number}/#{@feedbacks.total_pages}" %></p>
<table class="uk-table uk-table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Texto</th>
      <th>E-mail</th>
    </tr>
  </thead>
  <tbody>
    <%= for feedback <- @feedbacks.entries do %>
        <tr>
          <td>
            <%= link feedback.id, to: site_feedback_path(@conn, :show, URI.encode(@site.name), feedback.id), 
              class: "a" %>
          </td>
          <td>
            <%= feedback.text %>
          </td>
          <td>
            <%= feedback.email %>
          </td>
          <td class="text-right">
            <span>
              <%= link "", to: site_feedback_path(@conn, :delete, URI.encode(@site.name), feedback.id), 
                method: :delete, data: [confirm: "¿Estás seguro?"], 
                class: "el-menu-icon fa fa-trash-alt" %>
            </span>
          </td>
        </tr>
    <% end %>
  </tbody>
</table>

<%= case compare(@feedbacks.page_number, @feedbacks.total_pages) do %>
  <% :equal -> %>
    <span><%= link "", to: site_feedback_path(@conn, :index, @site, page: @feedbacks.page_number - 1), class: "el-arrow-icon fa fa-arrow-left fa-2x" %></span>
  <% :lesser -> %>
    <span><%= link "", to: site_feedback_path(@conn, :index, @site, page: @feedbacks.page_number + 1), class: "el-arrow-icon fa fa-arrow-left fa-2x" %></span>
    <span><%= link "", to: site_feedback_path(@conn, :index, @site, page: @feedbacks.page_number - 1), class: "el-arrow-icon fa fa-arrow-right fa-2x" %></span>
  <% :first -> %>
    <span><%= link "", to: site_feedback_path(@conn, :index, @site, page: @feedbacks.page_number + 1), class: "el-arrow-icon fa fa-arrow-right fa-2x" %></span>
  <% _ -> %>
<% end %>

<br>

<span><%= link "Regresar", to: site_path(@conn, :show, URI.encode(@site.name)) %></span>

lib/elephant_in_the_room_web/templates/feedback/show.html.eex
<h2><%= @feedback.id%></h2>

<ul>
  <li>
    <strong>E-Mail:</strong>
    <%= @feedback.email %>
  </li>
  <li>
    <strong>Texto:</strong>
    <%= @feedback.text %>
  </li>
</ul>

<span><%= link "Regresar", to: site_feedback_path(@conn, :index, URI.encode(@site.name)) %></span>